spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test
        username: test
        password: test
    jpa:
        hibernate:
        ddl-auto: create
        generate-ddl: true
        show-sql: true
        database: mysql
    server:
        port: 8080